"""empty message

Revision ID: 410a9bf29614
Revises: 6698ee55f539
Create Date: 2016-10-01 17:35:09.371593

"""

# revision identifiers, used by Alembic.
revision = '410a9bf29614'
down_revision = '6698ee55f539'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'category', ['name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category', type_='unique')
    ### end Alembic commands ###
