"""empty message

Revision ID: 6698ee55f539
Revises: None
Create Date: 2016-10-01 17:34:38.437665

"""

# revision identifiers, used by Alembic.
revision = '6698ee55f539'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('author', sa.Column('email', sa.String(length=120), nullable=True))
    op.create_unique_constraint(None, 'author', ['email'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'author', type_='unique')
    op.drop_column('author', 'email')
    op.drop_column('author', 'description')
    ### end Alembic commands ###
